---
name: CI
on: [push]

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: server.Dockerfile
          tags: |
            ghcr.io/strideynet/noughts-crosses-grpc-rust/server:latest
            ghcr.io/strideynet/noughts-crosses-grpc-rust/server:${{ github.sha }}
